apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
        - name: django
          image: mferral/django-api:lastest
          command: ['python', 'manage.py', 'migrate']
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: kubernetes_django
            - name: POSTGRES_HOST
              value: postgres          
      restartPolicy: Never
  backoffLimit: 5