apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-container
  template:
    metadata:
      labels:
        app: postgres-container
        tier: backend
    spec:
      containers:      
        - name: postgres-container
          image: postgres:10-alpine
          # command: ["/bin/chown","-R","1000", "/var/lib/postgresql/data"]    
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: kubernetes_django
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data              
              name: postgres-volume-mount
              subPathExpr: pgdata
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: data-pvc