apiVersion: v1
kind: Service
metadata:
  name: postgres 
spec:
  type: NodePort
  ports:
  - port: 5432
    # protocol: TCP
    targetPort: 5432
    # nodePort: 30003
  selector:
    app: postgres-container
    # role: postgres-container
    